default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: api_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: api_production
  username: api
  password: <%= ENV["API_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
